name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.16.0'

      - name: Install dependencies
        run: npm install
        working-directory: ./Project

      - name: Install Playwright browsers
        run: npx playwright install
        working-directory: ./Project

      - name: Install Playwright dependencies
        run: sudo npx playwright install-deps
        working-directory: ./Project

      - name: Start API server
        run: java -jar demo-0.0.1-SNAPSHOT.jar &
        working-directory: ./Project

      - name: Wait for API server to be ready
        run: |
          echo "Waiting for API server to be ready..."
          for i in {1..30}; do
            if curl -s http://localhost:7081/; then
              echo "API server is ready!"
              break
            fi
            echo "Waiting for API server..."
            sleep 5
          done
        working-directory: /

      - name: Run API tests
        run: npm run test:api
        working-directory: ./Project
        continue-on-error: true

      - name: Run UI tests
        run: npm run test:ui
        working-directory: ./Project
        continue-on-error: true

      - name: Generate UI HTML report
        run: npm run generate-ui-html-report
        working-directory: ./Project

      - name: Generate API HTML report
        run: npm run generate-api-html-report
        working-directory: ./Project

      - name: Stop API server
        run: pkill -f 'java -jar demo-0.0.1-SNAPSHOT.jar'
        working-directory: ./Project

      - name: Upload UI test report
        uses: actions/upload-artifact@v3
        with:
          name: ui-cucumber-report
          path: Project/reports/ui-cucumber-report.json

      - name: Upload API test report
        uses: actions/upload-artifact@v3
        with:
          name: api-cucumber-report
          path: Project/reports/api-cucumber-report.json
          
      - name: Upload UI HTML report
        uses: actions/upload-artifact@v3
        with:
          name: ui-cucumber-report-html
          path: Project/reports/ui-cucumber-report.html

      - name: Upload API HTML report
        uses: actions/upload-artifact@v3
        with:
          name: api-cucumber-report-html
          path: Project/reports/api-cucumber-report.html

      - name: Display instructions to open the report
        run: |
          echo "To view the test reports, download the HTML files from the 'Artifacts' section of the GitHub Actions run summary and open them in your browser."